name: Technobility 2.0
favicon: null
layout_spectrum: 0.017850949428975582
typography_spectrum: 0.020806337473914027
title: Peter de Jager
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: 28bf8d99-c3b4-42ff-8ce0-c62e9ccf6718
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c2045'
    - '#ffffff'
    - '#5f6380'
    - '#9397b2'
    - '#b8b9cb'
  brandStrength: 0.1875
  lightness: 0.37727727368474007
  saturation: 0.9314281549304724
  rhythmicContrast: 0
purpose: []
